Main.elm:
	elm make src/Main.elm --output=../server/resources/public/main.js

Tags.elm:
	elm make src/Tags.elm --output=../server/resources/public/tags.js

Filter.elm:
	elm make src/Filter.elm --output=../server/resources/public/filter.js
